//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitShortcutExpansion.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitShortcutExpansion.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Shortcuts&gt;
        ///  &lt;ShortcutItem CommandName=&quot;修改&quot; CommandId=&quot;ID_BUTTON_SELECT&quot; Shortcuts=&quot;MD&quot; Paths=&quot;创建&amp;gt;选择; 插入&amp;gt;选择; 注释&amp;gt;选择; 视图&amp;gt;选择; 管理&amp;gt;选择; 附加模块&amp;gt;选择; 修改&amp;gt;选择; 建筑&amp;gt;选择; 结构&amp;gt;选择; 钢&amp;gt;选择; 系统&amp;gt;选择; 分析&amp;gt;选择; 体量和场地&amp;gt;选择; 协作&amp;gt;选择; 上下文选项卡&amp;gt;选择&quot; /&gt;
        ///  &lt;ShortcutItem CommandName=&quot;选择链接&quot; CommandId=&quot;ID_TOGGLE_ALLOW_LINK_SELECTION&quot; Paths=&quot;创建&amp;gt;选择; 插入&amp;gt;选择; 注释&amp;gt;选择; 视图&amp;gt;选择; 管理&amp;gt;选择; 附加模块&amp;gt;选择; 修改&amp;gt;选择; 建筑&amp;gt;选择; 结构&amp;gt;选择; 钢&amp;gt;选择; 系统&amp;gt;选择; 分析&amp;gt;选择; 体量和场地&amp;gt;选择; 协作&amp;gt;选择; 上下文选项卡&amp;gt;选择&quot; /&gt;
        ///  &lt;Sho [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string shortcuts_Revit2019 {
            get {
                return ResourceManager.GetString("shortcuts_Revit2019", resourceCulture);
            }
        }
    }
}
